### ISSUE TITLE
希望添加开源协议

### ISSUE THREAD

**Issue by Jesse205** [epcdiy/timemachineplus#1]
希望添加一个开源协议，防止更多人侵权

**Comment by cytsai1008** [comment]
根据介绍影片要求二次制作也必须开源，我个人认为GPL是个不错的选择

**Comment by yuantuo666** [comment]
未设置许可证实际上是不允许任何人进行修改分发的，如果想要其他人参与其中应该选择正确的许可证

> However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.
> https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

**Comment by LJS08** [comment]
如果觉得选许可证太麻烦，可以直接在LICENSE上写二次发布要求，比如以原许可证发布，以合理的，便捷的方式提供源代码，注明原作者之类的。
以这样显式的方式授予使用者对源代码的权限等。

**Comment by epcdiy** [comment]
感谢指出，已添加GPL V3
